# Site settings
title: farez.ca
header-img: img/home-bg.jpg
email: info@farez.ca
description: "Nerd words about work and play"
baseurl: ""
url: "http://farez.ca"
twitter_username: farezv
github_username:  farezv
quora_username: Farez-Vadsaria

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
