name: "farez.ca"
description: Can't stop the signal
meta_description: "Nerd words of work and play"

markdown: redcarpet
highlighter: pygments
logo: false
paginate: 10
permalink: /:title/

# Details for the RSS feed generator
url:            'farez.ca'
author:         'farezv'
