# Site settings
title: farez.ca
header-img: img/soldneer.jpg
email: info@farez.ca
description: "Nerd words of work and play"
baseurl: ""
url: "http://farez.ca"
twitter_username: farezv
github_username:  farezv
quora_username: Farez-Vadsaria

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]